version: '0'
services:
  test-runner:
    build: frontend/
    dockerfile: Dockerfile.e2e
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    links:
      - selenium-hub
      - frontend
  frontend:
    environment:
      - NODE_ENV=development
    build: frontend/
    volumes: [ "./frontend:/app", "/app/node_modules" ]
    ports:
      - "80:3000"
    links:
      - backend
  backend:
    environment:
      - NODE_ENV=development
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB=postgres
      - DB_HOST=database
      - DB_PORT=5432
    build: backend/
    volumes: [ "./backend:/app" ]
    ports:
      - "81:5000"
    # expose:
    #   - "80:5000"
    links:
      - "db:database"
  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    ports:
      - "1024-65535:1024-65535"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
