version: '0'
services:
  frontend:
    environment:
      - NODE_ENV=development
    build: frontend/
    # depends_on:
    #   - backend
    volumes: [ "./frontend:/app", "/app/node_modules" ]
    ports:
      - "80:3000"
    links:
      - backend
  backend:
    environment:
      - NODE_ENV=development
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB=postgres
      - DB_HOST=database
      - DB_PORT=5432
    build: backend/
    volumes: [ "./backend:/app" ]
    ports:
      - "81:5000"
    expose:
      - "5000"
    links:
      - "db:database"
  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
