export const LOADSTATE = "LOADSTATE";
export const SAVESTATE = "SAVESTATE";

export const ADDMODELCITY = "ADDMODELCITY";
export const ADDMODELCOMMUTE = "ADDMODELCOMMUTE";
export const ADDMODELHOME = "ADDMODELHOME";

export const CLEARMODELS = "CLEARMODELS";

export const UPDATEFORMCITY = "UPDATEFORMCITY";
export const UPDATEFORMCOMMUTE = "UPDATEFORMCOMMUTE";
export const UPDATEFORMHOME = "UPDATEFORMHOME";

export const UPDATESELECTCITY = "UPDATESELECTCITY";
export const UPDATESELECTCOMMUTE = "UPDATESELECTCOMMUTE";
export const UPDATESELECTHOME = "UPDATESELECTHOME";

export const UPDATESEARCHBARVAL = "UPDATESEARCHBARVAL";